config/routes.rb
Rails.application.routes.draw do
  resources :urls
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/:vanity', to: 'vanity_redirect#detour'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
class Url < ApplicationRecord
  belongs_to :user
  validates :vanity, { exclusion: {in: [:urls, :users], message: "%{value} is reserved."}}
  validates :vanity, uniqueness: true
  validates :vanity, presence: true
  validates :vanity, format: { with: /\A[a-zA-Z0-9-]+\z/, message: "only allows letters, numbers and dashes" }
  validates :source, format: {
                with: %r(\A(http|https):\/\/|[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,6}(:[0-9]{1,5})?(\/.*)?$/ix\z),
                message: "only valid urls"
              }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :urls
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/http_auth_concern.rb
module HttpAuthConcern
  extend ActiveSupport::Concern
  included do
    before_action :http_authenticate
  end

  def http_authenticate
    authenticate_or_request_with_http_basic do |username, password|
      @active_user = User.find_by(username: username, password: password)
    end
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: %i[ show edit update destroy ]
  before_action :set_users, only: %i[ index new edit]
  before_action :set_user, only: %i[ show edit update destroy ]
  include HttpAuthConcern
  # GET /urls or /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1 or /urls/1.json
  def show
    @user = User.find(@url.user_id)
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
    if @active_user.nil? || @active_user != @user
      redirect_back(fallback_location: urls_path, alert: 'incorrect authentication')
    end
  end

  # POST /urls or /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to url_url(@url), notice: "Url was successfully created." }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1 or /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to url_url(@url), notice: "Url was successfully updated." }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1 or /urls/1.json
  def destroy
    if @active_user.nil? || @active_user != @user
      redirect_back(fallback_location: urls_path, alert: 'incorrect authentication') && return
    else
      @url.destroy
      redirect_to urls_url, notice: "Url was successfully destroyed."
    end
  end

  private
    def set_user
      @user = @url.user
    end
    def set_users
      @users = User.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def url_params
      params.require(:url).permit(:source, :vanity, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @urls = @user.urls
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/controllers/vanity_redirect_controller.rb
class VanityRedirectController < ApplicationController
  def detour
    url = Url.find_by(vanity: vanity_param)
    if url
      url.increment(:visits).save
      redirect_to url.source, status: :found, allow_other_host: true
    else
      render file: "#{Rails.application.root}/public/404.html",  status: 404
    end
  end

  def vanity_param
    params.require(:vanity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vanity_redirect_helper.rb
module VanityRedirectHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VanityUrl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <%if @active_user %>
      <p>Logged in as <%= @active_user.username %></p>
    <% end  %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_with(model: url) do |form| %>
  <% if url.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :source, style: "display: block" %>
    <%= form.text_area :source %>
  </div>

  <div>
    <%= form.label :vanity, style: "display: block" %>
    <%= form.text_field :vanity %>
  </div>

  <div>
    <%= form.label :user, style: "display: block" %>
    <%= form.collection_select :user_id, @users, :id, :username %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/urls/_url.html.erb
<div id="<%= dom_id url %>">
  <p>
    <strong>Source:</strong>
    <%= url.source %>
  </p>

  <p>
    <strong>Vanity:</strong>
    <%= url.vanity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= url.user.username %>
  </p>
  <p>
    <strong>Visits:</strong>
    <%= url.visits %>
  </p>


</div>

app/views/urls/edit.html.erb
<h1>Editing url</h1>

<%= render "form", url: @url %>

<br>

<div>
  <%= link_to "Show this url", @url %> |
  <%= link_to "Back to urls", urls_path %>
</div>

app/views/urls/index.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<h1>Urls</h1>

<div id="urls">
  <% @urls.each do |url| %>
    <%= render url %>
    <p>
      <%= link_to "Show this url", url %>
    </p>
  <% end %>
</div>

<%= link_to "New url", new_url_path %>

app/views/urls/new.html.erb
<h1>New url</h1>

<%= render "form", url: @url %>

<br>

<div>
  <%= link_to "Back to urls", urls_path %>
</div>

app/views/urls/show.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<%= render @url %>

<div>
  <%= link_to "Edit this url", edit_url_path(@url) %> |
  <%= link_to "Back to urls", urls_path %>

  <%= button_to "Destroy this url", @url, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password, type: 'password' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>
<% @urls.each do |url| %>
  <%= link_to url.vanity, url_path(url.id)  %>
<% end %>
<br />
<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>